{
 "title": "Cluster Backup Stats",
 "time": { "from": "now-1M", "to": "now" },
 "panels": [
  {
   "title": "Backup Time Per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\nsum((duration_usecs / 60000000)) as duration \nfrom reporting.protection_job_runs\ngroup by starttime\norder by starttime"
    }
   ]
  },
  {
   "title": "Backup Ingest Per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\nsum((source_delta_size_bytes / 1048576)) as data_read \nfrom reporting.protection_job_runs\ngroup by starttime\norder by starttime"
    },
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\nsum((data_written_size_bytes / 1048576)) as data_written\nfrom reporting.protection_job_runs\ngroup by starttime\norder by starttime"
    }
   ]
  },
  {
   "title": "Replication Physical Data Transferred",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\nsum((physical_size_bytes_transferred / 1048576)) as transferred\nfrom reporting.protection_job_run_replications\ngroup by starttime\norder by starttime"
    }
   ]
  },
  {
   "title": "Archival Physical Data Transferred",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\nsum((physical_size_bytes_transferred / 1048576)) as transferred\nfrom reporting.protection_job_run_archivals\ngroup by starttime\norder by starttime"
    }
   ]
  }
 ]
}