apiVersion: v1
kind: Pod
metadata:
  name: backup-service
  annotations:
    v1.multus-cni.io/default-network: cohesity-system-services
spec:
  containers:
  - name: backup-service
    image: backup-service
    imagePullPolicy: Never
    command: ["ping", "8.8.8.8"]
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password
    - name: MONGODB_CONNECT_STRING
      valueFrom:
        secretKeyRef:
          name: mongodb-mongodbuser-admin
          key: connectionString.standard
    - name: MONGODB_USER
      valueFrom:
        secretKeyRef:
          name: mongodb-mongodbuser-admin
          key: username
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-mongodbuser-admin
          key: password
    - name: RESTORE_S3_HOST
      valueFrom:
        secretKeyRef:
          name: restore-config
          key: host
    - name: RESTORE_S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: restore-config
          key: accesskey
    - name: RESTORE_S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: restore-config
          key: secretkey
    - name: RESTORE_S3_LOCATION
      valueFrom:
        secretKeyRef:
          name: restore-config
          key: location
    - name: RESTORE_S3_BUCKET
      valueFrom:
        secretKeyRef:
          name: restore-config
          key: bucket
    - name: S3_HOST
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: host
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: accesskey
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: secretkey
    - name: S3_LOCATION
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: location
    - name: S3_BUCKET
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: bucket
    - name: S3_RETENTION
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: retention
    - name: APPLIANCE_NAME
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: appliance-name
    - name: SMTP_SERVER
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: smtp-server
    - name: SMTP_PORT
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: smtp-port
    - name: SMTP_USER
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: smtp-user
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: smtp-password
    - name: SEND_FROM
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: smtp-from
    - name: SEND_TO
      valueFrom:
        secretKeyRef:
          name: backup-config
          key: smtp-to
