{
 "title": "Performance Dashboard",
 "time": { "from": "now-1M", "to": "now-1d" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as starttime,\ncpu_usage_percent as CPU\nfrom reporting.resource_usage_stats\nwhere entity_type = 1\norder by starttime"
    }
   ]
  },
  {
   "title": "Percent Full",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "select 100 * physical_usage_bytes / cluster_capacity_bytes as used_pct\nfrom reporting.cluster"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\n100 * count(status) filter (where status = 4 or status = 5) / count(status) as Succeeded\nfrom reporting.protection_job_run_entities\nGroup by starttime"
    }
   ]
  },
  {
   "title": "Avg Read Throughput",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) as day,\navg(read_throughput_bytes_per_sec) as average_read_throughput\nfrom reporting.io_performance_stats\nwhere entity_type = 1\ngroup by day"
    }
   ]
  },
  {
   "title": "Avg Write Throughput",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) as day,\navg(write_throughput_bytes_per_sec) as average_write_throughput\nfrom reporting.io_performance_stats\nwhere entity_type = 1\ngroup by day"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as starttime,\nmemory_usage_percent as Memory\nfrom reporting.resource_usage_stats\nwhere entity_type = 1\norder by starttime"
    }
   ]
  },
  {
   "title": "Backup Failure Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\n100 * count(status) filter (where status = 6) / count(status) as Failed\nfrom reporting.protection_job_run_entities\nGroup by starttime"
    }
   ]
  },
  {
   "title": "Max Read Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) as day,\nmax(read_latency_msecs) as max_read_latency\nfrom reporting.io_performance_stats\nwhere entity_type = 1 and date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) != date_trunc('day', now())\ngroup by day\norder by day"
    }
   ]
  },
  {
   "title": "Max Write Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) as day,\nmax(write_latency_msecs) as max_write_latency\nfrom reporting.io_performance_stats\nwhere entity_type = 1 and date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) != date_trunc('day', now())\ngroup by day\norder by day"
    }
   ]
  },
  {
   "title": "Max Read IOPs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) as day,\nmax(read_iops) as max_read_iops\nfrom reporting.io_performance_stats\nwhere entity_type = 1 and date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) != date_trunc('day', now())\ngroup by day\norder by day"
    }
   ]
  },
  {
   "title": "Max Write IOPs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) as day,\nmax(write_iops) as max_write_iops\nfrom reporting.io_performance_stats\nwhere entity_type = 1 and date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) != date_trunc('day', now())\ngroup by day\norder by day"
    }
   ]
  }
 ]
}