{
 "title": "Backup Success Rate",
 "time": { "from": "now-1M", "to": "now" },
 "panels": [
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\n100 * count(status) filter (where status = 4 or status = 5) / count(status) as Succeeded\nfrom reporting.protection_job_run_entities\nGroup by starttime"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\n100 * count(status) filter (where status = 3) / count(status) as Canceled,\n100 * count(status) filter (where status = 4) / count(status) as Succeeded,\n100 * count(status) filter (where status = 5) / count(status) as SucceededWithWarning,\n100 * count(status) filter (where status = 6) / count(status) as Failed\nfrom reporting.protection_job_run_entities\nGroup by starttime"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\n100 * count(status) filter (where status = 6) / count(status) as Failed\nfrom reporting.protection_job_run_entities\nGroup by starttime"
    }
   ]
  },
  {
   "title": "Backup Failure Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 4, "y": 8 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(start_time_usecs / 1000000)) as starttime,\ncount(status) filter (where status = 3) as Canceled,\ncount(status) filter (where status = 5) as SucceededWithWarning,\ncount(status) filter (where status = 6) as Failed\nfrom reporting.protection_job_run_entities\nGroup by starttime"
    }
   ]
  }
 ]
}