{
 "title": "Cluster Resource Dashboard",
 "time": { "from": "2022-10-03T07:00:00.000Z", "to": "2022-11-22T08:00:00.000Z" },
 "panels": [
  {
   "title": "Percent Full",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "select 100 * physical_usage_bytes / cluster_capacity_bytes as used_pct\nfrom reporting.cluster"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as starttime,\ncpu_usage_percent as CPU\nfrom reporting.resource_usage_stats\nwhere entity_type = 1\norder by starttime"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as starttime,\nmemory_usage_percent as Memory\nfrom reporting.resource_usage_stats\nwhere entity_type = 1\norder by starttime"
    }
   ]
  },
  {
   "title": "Cluster Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select date_trunc('day', to_timestamp(timestamp_usecs / 1000000)) as starttime,\nlocal_total_physical_usage_bytes as used,\n(select cluster_capacity_bytes from reporting.cluster) as capacity\nfrom reporting.storage_usage_stats\nwhere entity_type = 1\norder by starttime"
    },
    {
     "rawSql": "select cluster_capacity_bytes as capacity\nfrom reporting.cluster"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as starttime,\ncpu_usage_percent as cpu,\nmemory_usage_percent as memory\nfrom reporting.resource_usage_stats\nwhere entity_type = 1\norder by starttime"
    }
   ]
  }
 ]
}